CREATE DATABASE jukebox
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `tracks` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `duration` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `youtubeID` VARCHAR(255) NULL
)