CREATE DATABASE jukebox
  ENCODING 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8';

CREATE USER jukebox WITH PASSWORD 'jukebox';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jukebox;

CREATE TABLE IF NOT EXISTS tracks (
  id SERIAL PRIMARY KEY,
  duration INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  youtube_id VARCHAR(20) NULL DEFAULT NULL,
  vevo_id VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS artists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url_safe_name VARCHAR(255) NOT NULL,
  is_vevo BOOL NOT NULL DEFAULT FALSE,
  official_website VARCHAR(255) NULL DEFAULT NULL,
  twitter VARCHAR(255) NULL DEFAULT NULL,
  facebook VARCHAR(255) NULL DEFAULT NULL,
  itunes VARCHAR(255) NULL DEFAULT NULL,
  amazon VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS track_artists (
  id SERIAL PRIMARY KEY,
  artist INT NOT NULL,
  track INT NOT NULL,
  role VARCHAR(11),
  FOREIGN KEY (artist) REFERENCES artists(id),
  FOREIGN KEY (track) REFERENCES tracks(id),
  CHECK (role IN ('main', 'featured'))
);

CREATE TABLE IF NOT EXISTS genres (
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS track_genres (
  id SERIAL PRIMARY KEY,
  track INT NOT NULL,
  genre INT NOT NULL,
  FOREIGN KEY (track) REFERENCES tracks(id),
  FOREIGN KEY (genre) REFERENCES genres(id)
);
